### ISSUE TITLE
ürün gönderimi

### ISSUE THREAD

**Issue by oldiscool** [halilsafakkilic/pttavm-api-php-client#1]
merhaba, elinize sağlık.
ürün gönderimi için örnek verebilmeniz mümkün mü?

**Comment by halilsafakkilic** [comment]
Merhaba, teşekkürler. 

https://github.com/halilsafakkilic/pttavm-api-php-client/commit/8340aeb8dbd15d3d2fadd26cc66cbbe7121a1839 ile birlikte ürün gönderimi örneği eklendi.
